# ZMK Firmware Build Matrix
# -------------------------
# Each keyboard section defines the board/shield combinations to build.
# Use artifact-name to distinguish outputs when the same shield is used
# with different boards or configurations.
#
# Available options per entry:
#   - board: controller board (required)
#   - shield: keyboard shield (required for split/shield keyboards)
#   - snippet: zephyr snippet (e.g., studio-rpc-usb-uart)
#   - cmake-args: additional cmake flags
#   - artifact-name: custom name for the build artifact
---
include:
  # ─────────────────────────────────────────────────────────────────────
  # Keyball44 (split 44-key with trackball)
  # Board: nice!nano v2 | Shield: keyball_nano
  # ─────────────────────────────────────────────────────────────────────
  - board: nice_nano_v2
    shield: keyball44_left nice_view_adapter nice_view
    artifact-name: keyball44_left-nice_nano_v2

  - board: nice_nano_v2
    shield: keyball44_right nice_view_adapter nice_view
    snippet: studio-rpc-usb-uart
    artifact-name: keyball44_right-nice_nano_v2

  # ─────────────────────────────────────────────────────────────────────
  # Utilities
  # ─────────────────────────────────────────────────────────────────────
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: settings_reset-nice_nano_v2
